
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.18.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace OpenCCSharp.ConsoleApp {
    using System;
    using Terminal.Gui;
    
    
    public partial class MainWindow : Terminal.Gui.Window {
        
        private Terminal.Gui.Label label1;
        
        private Terminal.Gui.ComboBox variantComboBox1;
        
        private Terminal.Gui.ComboBox variantComboBox2;
        
        private Terminal.Gui.TextView textView1;
        
        private Terminal.Gui.TextView textView2;
        
        private Terminal.Gui.Button swapButton;
        
        private Terminal.Gui.Button exitButton;
        
        private void InitializeComponent() {
            this.exitButton = new Terminal.Gui.Button();
            this.swapButton = new Terminal.Gui.Button();
            this.textView2 = new Terminal.Gui.TextView();
            this.textView1 = new Terminal.Gui.TextView();
            this.variantComboBox2 = new Terminal.Gui.ComboBox();
            this.variantComboBox1 = new Terminal.Gui.ComboBox();
            this.label1 = new Terminal.Gui.Label();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.Text = "";
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = true;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "OpenCC# Console App";
            this.label1.Width = 4;
            this.label1.Height = 1;
            this.label1.X = 1;
            this.label1.Y = 0;
            this.label1.Data = "label1";
            this.label1.Text = "字形转换";
            this.label1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label1);
            this.variantComboBox1.Width = Dim.Percent(50f) - 2;
            this.variantComboBox1.Height = Dim.Percent(50f);
            this.variantComboBox1.X = 1;
            this.variantComboBox1.Y = 2;
            this.variantComboBox1.Data = "variantComboBox1";
            this.variantComboBox1.Text = "";
            this.variantComboBox1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.variantComboBox1);
            this.variantComboBox2.Width = Dim.Fill(1);
            this.variantComboBox2.Height = Dim.Percent(50f);
            this.variantComboBox2.X = Pos.Percent(50f);
            this.variantComboBox2.Y = 2;
            this.variantComboBox2.Data = "variantComboBox2";
            this.variantComboBox2.Text = "";
            this.variantComboBox2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.variantComboBox2);
            this.textView1.Width = Dim.Percent(50f) - 2;
            this.textView1.Height = Dim.Fill(2);
            this.textView1.X = 1;
            this.textView1.Y = 4;
            this.textView1.AllowsTab = true;
            this.textView1.AllowsReturn = true;
            this.textView1.WordWrap = true;
            this.textView1.Data = "textView1";
            this.textView1.Text = "";
            this.textView1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.textView1);
            this.textView2.Width = Dim.Fill(1);
            this.textView2.Height = Dim.Fill(2);
            this.textView2.X = Pos.Percent(50f);
            this.textView2.Y = 4;
            this.textView2.AllowsTab = true;
            this.textView2.AllowsReturn = true;
            this.textView2.WordWrap = true;
            this.textView2.Data = "textView2";
            this.textView2.Text = "";
            this.textView2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.textView2);
            this.swapButton.Width = 16;
            this.swapButton.X = Pos.Center();
            this.swapButton.Y = Pos.Percent(100f) - 1;
            this.swapButton.Data = "swapButton";
            this.swapButton.Text = "<- 交换(_S) ->";
            this.swapButton.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.swapButton.IsDefault = false;
            this.Add(this.swapButton);
            this.exitButton.Width = 10;
            this.exitButton.X = Pos.Right(swapButton) + 1;
            this.exitButton.Y = Pos.Top(swapButton);
            this.exitButton.Data = "exitButton";
            this.exitButton.Text = "退出(_E)";
            this.exitButton.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.exitButton.IsDefault = false;
            this.Add(this.exitButton);
        }
    }
}
