name: OpenCCSharp CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '*.txt'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '*.txt'
  schedule:
    - cron: "7 0 * * MON"

jobs:
  build_and_test:
    name: Build & Test
    timeout-minutes: 30
    strategy:
      matrix:
        runs-on: ["ubuntu-latest", "windows-latest"]
        config: ["Debug", "Release"]
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            5.0.x
            6.0.x
      - name: Build
        shell: pwsh
        run: "./OpenCCSharp.Commons/CI/Build.ps1 -Configuration ${{ matrix.config }}"
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "OpenCCSharp-${{ matrix.config }}"
          path: ./OpenCCSharp.*/bin/
      - name: Test
        shell: pwsh
        run: "./OpenCCSharp.Commons/CI/Test.ps1 -Configuration ${{ matrix.config }}"

