name: OpenCCSharp CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "*.txt"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "*.txt"
  schedule:
    - cron: "23 0 1 * *"

jobs:
  build_and_test:
    name: "Build & Test: ${{ matrix.os }} / ${{ matrix.config }}"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        config: ["Debug", "Release"]
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      OCCS_IS_CI_BUILD: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x
            8.0.x
          include-prerelease: true
      - name: Build
        shell: pwsh
        run: "./OpenCCSharp.Commons/CI/Build.ps1 -Configuration ${{ matrix.config }}"
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: "OpenCCSharp-build-${{ matrix.os }}-${{ matrix.config }}"
          path: |
            ./OpenCCSharp.*/bin/
            ./OpenCCSharp.*/obj/
      - name: Upload NuGet packages
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: "OpenCCSharp-packages-${{ matrix.os }}-${{ matrix.config }}"
          path: |
            ./OpenCCSharp.*/bin/*/*.nupkg
            ./OpenCCSharp.*/bin/*/*.snupkg
      - name: Test
        shell: pwsh
        run: "./OpenCCSharp.Commons/CI/Test.ps1 -Configuration ${{ matrix.config }}"
